function tests = test_normalize_degree
    %TEST_NORMALIZE_DEGREE Shared scalar and direction-wise degree contract.
    tests = functiontests(localfunctions);
end

function testScalarExpandsAndVectorsNormalizeToRows(testCase)
    % Scalars expand uniformly and vector orientation is not public state.
    testCase.verifyEqual( ...
        helper.normalizeDegree(2, 3, "test:InvalidDegree", "Degree"), ...
        [2 2 2]);
    testCase.verifyEqual( ...
        helper.normalizeDegree([0; 2; 1], 3, ...
        "test:InvalidDegree", "Degree"), [0 2 1]);
    testCase.verifyEqual( ...
        helper.normalizeDegree([3 1 0], 3, ...
        "test:InvalidDegree", "Degree"), [3 1 0]);
end

function testInvalidInputsPreserveCallerError(testCase)
    % Reject every shape and value outside scalar-or-ell-vector degrees.
    bad = {[], [1 2], [1 2; 3 4], -1, 0.5, Inf, NaN, 1i, ...
        "one", true};
    for k = 1:numel(bad)
        testCase.verifyError(@() helper.normalizeDegree( ...
            bad{k}, 3, "test:InvalidDegree", "Degree"), ...
            "test:InvalidDegree");
    end
end
