import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const manualPath = join(root, "doc", "manual.tex");
const outputPath = join(here, "..", "src", "data", "version.js");

const manual = readFileSync(manualPath, "utf8");
const match = manual.match(/\\author\{\s*Version\s+([^}]+?)\s*\}/i);

if (!match) {
  throw new Error("Could not find a manual version in doc/manual.tex author metadata.");
}

const manualVersion = match[1].trim();
const source = `// Generated by scripts/sync-version.mjs from doc/manual.tex.
// Do not edit the current version by hand.

export const versionInfo = {
  current: ${JSON.stringify(manualVersion)},
  source: "doc/manual.tex",
  sourcePattern: "\\\\author{Version ...}",
};
`;

writeFileSync(outputPath, source);
console.log(`Synced manual version ${manualVersion} to ${outputPath}`);
