function out = mkRhodiff(obj, deg, vals, rb, hasDec)
    %MKRHODIFF Rebuild a base-class derivative result.

    out = pdbase(obj.GridInfo.Vectors, obj.MatrixSize, deg, vals, ...
        IsContinuous=false, ContainsDecision=hasDec, ...
        HasRateDependence=true, RateBounds=rb, ...
        SourceSummary="derivative");
end
