function init = mkInit(grid, sz, deg, vals, hasDec, hasRate, rb, summary, options)
    %MKINIT Package prepared coefficient data for the dpvar constructor.
    arguments
        grid
        sz
        deg
        vals
        hasDec
        hasRate
        rb
        summary
        options.IsContinuous (1, 1) logical = true
        options.DerivativeSourceDegree = []
    end

    init = struct( ...
        "DpvarInternal", true, ...
        "Grid", {grid}, ...
        "MatrixSize", sz, ...
        "Degree", deg, ...
        "LocalValues", {vals}, ...
        "ContainsDecision", hasDec, ...
        "HasRateDependence", hasRate, ...
        "RateBounds", rb, ...
        "SourceSummary", summary, ...
        "IsContinuous", options.IsContinuous, ...
        "DerivativeSourceDegree", options.DerivativeSourceDegree);
end
