function init = mkInit(grid, sz, deg, vals, hasDec, hasRate, rb, summary)
    %MKINIT Package prepared coefficient data for the dpvar constructor.

    init = struct( ...
        "DpvarInternal", true, ...
        "Grid", {grid}, ...
        "MatrixSize", sz, ...
        "Degree", deg, ...
        "LocalValues", {vals}, ...
        "ContainsDecision", hasDec, ...
        "HasRateDependence", hasRate, ...
        "RateBounds", rb, ...
        "SourceSummary", summary);
end
