function init = mkInit(grid, sz, deg, vals, hasDec, hasRate, rb, summary, isCont)
    %MKINIT Package prepared coefficient data for the dpvar constructor.

    if nargin < 9
        isCont = true;
    end

    init = struct( ...
        "DpvarInternal", true, ...
        "Grid", {grid}, ...
        "MatrixSize", sz, ...
        "Degree", deg, ...
        "LocalValues", {vals}, ...
        "IsContinuous", isCont, ...
        "ContainsDecision", hasDec, ...
        "HasRateDependence", hasRate, ...
        "RateBounds", rb, ...
        "SourceSummary", summary);
end
