#!/usr/bin/env python3
"""Generate or verify the TeX projection of the manual terminology registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SUPPORT = ROOT / "support"
REGISTRY = SUPPORT / "terminology.json"
OUTPUT = SUPPORT / "terminology.tex"


HEADER = r"""% Generated by generate_terminology.py from terminology.json. Do not edit directly.
\makeatletter
\newcommand{\DeclareManualTerm}[5]{%
  \expandafter\gdef\csname manualterm@#1@abbr\endcsname{#2}%
  \expandafter\gdef\csname manualterm@#1@long\endcsname{#3}%
  \expandafter\gdef\csname manualterm@#1@index\endcsname{#4}%
  \expandafter\gdef\csname manualterm@#1@anchor\endcsname{#5}}
\newcommand{\manualtermcheck}[1]{%
  \@ifundefined{manualterm@#1@abbr}{\PackageError{grid-lmia-manual}{Unknown terminology key `#1'}{Add the key to terminology.json and regenerate terminology.tex.}}{}}
\newcommand{\termdef}[1]{%
  \manualtermcheck{#1}%
  \csname manualterm@#1@long\endcsname{} (\csname manualterm@#1@abbr\endcsname)%
  \index{\csname manualterm@#1@index\endcsname}%
  \index{\csname manualterm@#1@abbr\endcsname|see{\csname manualterm@#1@index\endcsname}}}
\newcommand{\term}[1]{%
  \manualtermcheck{#1}%
  \csname manualterm@#1@abbr\endcsname%
  \index{\csname manualterm@#1@index\endcsname}}
\newcommand{\termwebanchor}[1]{\manualtermcheck{#1}\csname manualterm@#1@anchor\endcsname}
"""


def tex_escape(value: str) -> str:
    return value.replace("#", r"\#").replace("%", r"\%")


def render() -> str:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    lines = [HEADER.rstrip(), ""]
    required = {"id", "abbreviation", "expansion", "aliases", "tex_index_key", "web_definition_anchor", "auto_link"}
    seen: set[str] = set()
    for term in data["terms"]:
        missing = sorted(required - term.keys())
        if missing:
            raise ValueError(f"term {term.get('id', '<unknown>')} misses {missing}")
        term_id = term["id"]
        if term_id in seen:
            raise ValueError(f"duplicate term id: {term_id}")
        seen.add(term_id)
        fields = [term_id, term["abbreviation"], term["expansion"], term["tex_index_key"], term["web_definition_anchor"]]
        lines.append(r"\DeclareManualTerm{" + "}{".join(tex_escape(str(field)) for field in fields) + "}")
    lines.extend([r"\makeatother", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when terminology.tex is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("terminology.tex is stale; run: python doc/generate_terminology.py")
            return 1
        term_count = expected.count(r"\DeclareManualTerm") - 1
        print(f"terminology projection is current ({term_count} terms)")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
