function init = mkInit(grid, sz, deg, vals, hasDec, hasRate, rb, summary, isCont)
    %MKINIT Package prepared coefficient data for the pdvar constructor.
    %
    %   Syntax:
    %     init = mkInit(grid, sz, deg, vals, hasDec, hasRate, rb, summary, isCont)
    %
    %   Example (via public algebra):
    %     P = pdvar(1, {[0 1]});
    %     Q = -P;  % Unary algebra packages data through mkInit.


    if nargin < 9
        isCont = true;
    end

    init = struct( ...
        "PdvarInternal", true, ...
        "Grid", {grid}, ...
        "MatrixSize", sz, ...
        "Degree", deg, ...
        "LocalValues", {vals}, ...
        "IsContinuous", isCont, ...
        "ContainsDecision", hasDec, ...
        "HasRateDependence", hasRate, ...
        "RateBounds", rb, ...
        "SourceSummary", summary);
end
